<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <AssemblyName>VideoWallpaper</AssemblyName>
    <RootNamespace>VideoWallpaper</RootNamespace>
    <TieredPGO>false</TieredPGO>
    <GCConserveMemory>7</GCConserveMemory>
    <ServerGarbageCollector>false</ServerGarbageCollector>
    <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp.WinForms" Version="3.9.*" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.*" />
  </ItemGroup>

</Project>
